[project]
name = "apotheclean"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "sqlalchemy>=2.0.46",
]

[tool.flake8]
max-line-length = 120
